DROP TABLE IF EXISTS pulses;
DROP TABLE IF EXISTS config;

CREATE TABLE pulses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  gpiopin INTEGER NOT NULL,
  pulses INTEGER NOT NULL
);

CREATE INDEX idx_pulses_gpiopin ON pulses (gpiopin);

CREATE TABLE config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  gpiopin INTEGER NOT NULL,
  name TEXT NOT NULL,
  type INTEGER NOT NULL,
  power INTEGER NOT NULL,
  energy INTEGER NOT NULL,
  time2 INTEGER NOT NULL,
  energy2 INTEGER NOT NULL
);